### ISSUE TITLE
next 12

### ISSUE THREAD

**Issue by enkhee** [Telsho/react-google-flight-datepicker#45]
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, no
n-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-
ssr for common fixes.

**Comment by Telsho** [comment]
Should be solved now, closing the issue
