### ISSUE TITLE
Issue - Not compatible with React versions 17 and above

### ISSUE THREAD

**Issue by Mat-dm** [Telsho/react-google-flight-datepicker#67]
Hello,

After several attempts, I discovered that `react-google-flight-datepicker` is not compatible with React versions 17 and above.
This following issue appear while selecting a date on mobile view:

ERROR
Cannot read properties of null (reading 'current')
TypeError: Cannot read properties of null (reading 'current')
    at HTMLDivElement.<anonymous> (http://localhost:3000/static/js/bundle.js:217109:21)

SCREENSHOT
![image](https://github.com/davidtran/react-google-flight-datepicker/assets/88112691/c8a69718-26f5-49e4-8c32-d8a62c0d505e)

-----

Let me know if I can provide any information.
Thanks for your help

**Comment by tidundun** [comment]
@Mat-dm I've got the same issue here. Did it work for you on lower versions?

**Comment by Mat-dm** [comment]
Yes, you have to go back to a previous version, it will work

Le lun. 22 avr. 2024 à 16:05, Stefan Wisełka ***@***.***> a
écrit :

**Comment by MriV13** [comment]
@Mat-dm Thanks
which version are you using?

**Comment by Mat-dm** [comment]
I think it's 15

Le lun. 22 avr. 2024 à 16:41, Stefan Wisełka ***@***.***> a
écrit :

**Comment by Telsho** [comment]
It's now compatible with version 18 and above, closing the issue
